### PR TITLE
Add login field select page and router path '/login' features

### PR DESCRIPTION
**Pull request by BarryAlanPan**
* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Add feature: login process's field (domain) select page, and the path '/login' for temporary testing goal.
4/11/2023 updated: 
- Add username/password login page.
- Conversion of login function by using input instead of hardcode.
- Auto verification before fetching schema data.
- Logout function works in sidebar button.

* **What is the current behavior?** (You can also link to an open issue here)
Instead of hardcode username/password, input ones are used in authentication.
#17 

* **What is the new behavior (if this is a feature change)?**
A domain select and username/password input is being used here before going to homepage.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
A login behaviour is needed before seeing content.

* **Add screenshot if possible.** (Add screenshot of the change)
field select page
**field select page**
Visible error report
**Visible error report**
Entered field name will be stored in sessionStorage
**Entered field name will be stored in sessionStorage**
CleanShot 2023-11-04 at 20 38 38@2x
**Login procedure comparison**

* **Other information**:
None

### CODE REVIEW

**Comment by Turtiainen** [comment]
@BarryAlanPan can you please link this pull request to correct user story if you cannot find anything that would match this, message me and we can create something suitable for this pull request. Also  remember to assign the user story for you.

**Comment by Turtiainen** [comment]
DO NOT MERGE! We are fine fine tuning user stories with @BarryAlanPan.

**Comment by BarryAlanPan** [comment]
DO NOT MERGE! Making final comfirmation.

**Comment by Turtiainen** [comment]
Merge review done. Looks good. Comments are missing, but do not prevent merging. (Can be added on separate pull request). Great work 🍻!

**Pull request merged**
